name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Hello World Script
      run: |
        chmod +x hello-world.sh
        ./hello-world.sh

    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Lint Script with ShellCheck
      run: |
        shellcheck hello-world.sh
